# This is a basic workflow to help you get started with Actions

name: Pull Request CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  test:

    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
